test_rag:
  image: python:3.12.9-slim
  stage: test
  script:
    - cd rag
    - pip install -r ../requirements-dev.txt
    - pytest --junitxml=junit.xml --cov=src
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

test_qna:
  image: python:3.12.9-slim
  stage: test
  script:
    - cd QnA
    - pip install -r ../requirements-dev.txt
    - pytest --junitxml=junit.xml --cov=src
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml