
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qna-deployment
  labels:
    app: qna
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qna
  template:
    metadata:
      labels:
        app: qna
    spec:
      containers:
        - name: qna
          image: qna-image:1.0
          ports:
            - containerPort: 8000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: agents-secret
                  key: OPENAI_API_KEY
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: agents-secret
                  key: GROQ_API_KEY
            - name: YUGABYTE_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: agents-configmap
                  key: YUGABYTE_DB_URL
            - name: MODEL
              valueFrom:
                configMapKeyRef:
                  name: agents-configmap
                  key: MODEL
            - name: RAG_AGENT_URL
              valueFrom:
                configMapKeyRef:
                  name: agents-configmap
                  key: RAG_AGENT_URL
            - name: OPENAI_MODEL_NAME
              valueFrom:
                configMapKeyRef:
                  name: agents-configmap
                  key: OPENAI_MODEL_NAME

---
apiVersion: v1
kind: Service
metadata:
  name: qna-service
spec:
  selector:
    app: qna
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
